jQuery(document).ready(function() {
    var jsFolder = "https://amazingslider.com/wp-content/uploads/amazingslider/2/sliderengine/";
    var skinsfoldername = "";
    var skinsfolder = "";
    if (jQuery("#amazingslider-2").length > 0) {
        jQuery("#amazingslider-2").amazingslider({
            jsfolder: '',
            skinsfoldername: 'images/slider',
            width: 510,
            height: 262,
            loadimageondemand: false,
            isresponsive: true,
            autoplayvideo: false,
            pauseonmouseover: false,
            randomplay: false,
            slideinterval: 5000,
            transitiononfirstslide: false,
            loop: 0,
            autoplay: false,
            navplayvideoimage: "play-32-32-0.png",
            navpreviewheight: 60,
            timerheight: 2,
            skin: "Classic",
            addgooglefonts: true,
            navshowplaypause: true,
            navshowplayvideo: true,
            navbuttonradius: 0,
            navpreviewposition: "top",
            navradius: 0,
            showshadow: false,
            navfeaturedarrowimagewidth: 16,
            navpreviewwidth: 192,
            googlefonts: "Inder",
            navcolor: "#999999",
            arrowwidth: 32,
            navmargin: 16,
            navspacing: 8,
            playvideoimage: "playvideo-64-64-0.png",
            ribbonimage: "ribbon_topleft-0.png",
            navwidth: 48,
            navheight: 48,
            timeropacity: 0.6,
            navpreviewbordercolor: "#fafafa",
            ribbonposition: "topleft",
            arrowstyle: "mouseover",
            navswitchonmouseover: false,
            navarrowimage: "navarrows-28-28-0.png",
            arrowimage: "arrows-32-32-0.png",
            playvideoimageheight: 64,
            navfonthighlightcolor: "#666666",
            showbackgroundimage: false,
            navpreviewborder: 4,
            shadowcolor: "#aaaaaa",
            navbuttonshowbgimage: true,
            navbuttonbgimage: "navbuttonbgimage-28-28-0.png",
            playvideoimagewidth: 64,
            navborder: 2,
            bottomshadowimagewidth: 110,
            showtimer: true,
            navshowpreview: false,
            navpreviewarrowheight: 8,
            navfeaturedarrowimage: "featuredarrow-16-8-0.png",
            showribbon: false,
            navfeaturedarrowimageheight: 8,
            descriptioncss: "display:block; position:relative; font:14px Inder,Arial,Tahoma,Helvetica,sans-serif; color:#333;",
            navplaypauseimage: "navplaypause-28-28-0.png",
            backgroundimagetop: -10,
            timercolor: "#fafafa",
            navfontsize: 12,
            navhighlightcolor: "#333333",
            navimage: "bullet-24-24-5.png",
            navbuttoncolor: "#999999",
            navshowarrow: true,
            navshowfeaturedarrow: true,
            titlecss: "display:block; position:relative; font: 16px Inder,Arial,Tahoma,Helvetica,sans-serif; color:#000;",
            shadowsize: 5,
            arrowhideonmouseleave: 1000,
            navopacity: 0.8,
            backgroundimagewidth: 120,
            bordercolor: "#fafafa",
            arrowheight: 32,
            arrowmargin: 8,
            bottomshadowimage: "bottomshadow-110-95-4.png",
            border: 6,
            timerposition: "bottom",
            navfontcolor: "#333333",
            borderradius: 0,
            navbuttonhighlightcolor: "#333333",
            navbordercolor: "#fafafa",
            navpreviewarrowimage: "previewarrow-16-8-0.png",
            navdirection: "horizontal",
            backgroundimage: "",
            navposition: "bottom",
            navpreviewarrowwidth: 16,
            bottomshadowimagetop: 95,
            navshowbuttons: false,
            navthumbtitlewidth: 120,
            navthumbnavigationstyle: "arrow",
            navthumbstyle: "imageonly",
            navstyle: "thumbnails",
            navthumbnavigationarrowimagewidth: 32,
            navthumbtitlehovercss: "text-decoration:underline;",
            navthumbnavigationarrowimage: "carouselarrows-32-32-0.png",
            navthumbdescriptioncss: "display:block;position:relative;padding:2px 4px;text-align:left;font:normal 12px Arial,Helvetica,sans-serif;color:#333;",
            navthumbtitleheight: 20,
            navthumbnavigationarrowimageheight: 32,
            navthumbtitlecss: "display:block;position:relative;padding:2px 4px;text-align:left;font:bold 14px Arial,Helvetica,sans-serif;color:#333;",
            textcss: "display:none;",
            ribbonmarginy: 0,
            ribbonmarginx: 0,
            fade: {
                duration: 1000,
                easing: "easeOutCubic",
                checked: true
            },
            transition: "fade"
        });
    }
});